// Copyright 2020 Red Hat, Inc
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.)

package v0_8_exp

import (
	"fmt"
	"os"
	slashpath "path"
	"path/filepath"
	"regexp"
	"strings"
	"text/template"

	baseutil "github.com/coreos/butane/base/util"
	"github.com/coreos/butane/config/common"
	"github.com/coreos/butane/translate"

	"github.com/coreos/go-systemd/v22/unit"
	"github.com/coreos/ignition/v2/config/util"
	"github.com/coreos/ignition/v2/config/v3_7_experimental/types"
	"github.com/coreos/vcontext/path"
	"github.com/coreos/vcontext/report"
)

var (
	mountUnitTemplate = template.Must(template.New("unit").Parse(`
{{- define "options" }}
  {{- if or .MountOptions .Remote }}
Options=
    {{- range $i, $opt := .MountOptions }}
      {{- if $i }},{{ end }}
      {{- $opt }}
    {{- end }}
    {{- if .Remote }}{{ if .MountOptions }},{{ end }}_netdev{{ end }}
  {{- end }}
{{- end -}}

# Generated by Butane
{{- if .Swap }}
[Swap]
What={{.Device}}
{{- template "options" . }}

[Install]
RequiredBy=swap.target
{{- else }}
[Unit]
Requires=systemd-fsck@{{.EscapedDevice}}.service
After=systemd-fsck@{{.EscapedDevice}}.service

[Mount]
Where={{.Path}}
What={{.Device}}
Type={{.Format}}
{{- template "options" . }}

[Install]
{{- if .Remote }}
RequiredBy=remote-fs.target
{{- else }}
RequiredBy=local-fs.target
{{- end }}
{{- end }}`))
)

// ToIgn3_7Unvalidated translates the config to an Ignition config. It also returns the set of translations
// it did so paths in the resultant config can be tracked back to their source in the source config.
// No config validation is performed on input or output.
func (c Config) ToIgn3_7Unvalidated(options common.TranslateOptions) (types.Config, translate.TranslationSet, report.Report) {
	ret := types.Config{}

	tr := translate.NewTranslator("yaml", "json", options)
	tr.AddCustomTranslator(translateIgnition)
	tr.AddCustomTranslator(translateFile)
	tr.AddCustomTranslator(translateDirectory)
	tr.AddCustomTranslator(translateLink)
	tr.AddCustomTranslator(translateResource)
	tr.AddCustomTranslator(translatePasswdUser)
	tr.AddCustomTranslator(translateUnit)

	tm, r := translate.Prefixed(tr, "ignition", &c.Ignition, &ret.Ignition)
	tm.AddTranslation(path.New("yaml", "version"), path.New("json", "ignition", "version"))
	tm.AddTranslation(path.New("yaml", "ignition"), path.New("json", "ignition"))
	translate.MergeP2(tr, tm, &r, "kernel_arguments", &c.KernelArguments, "kernelArguments", &ret.KernelArguments)
	translate.MergeP(tr, tm, &r, "passwd", &c.Passwd, &ret.Passwd)
	translate.MergeP(tr, tm, &r, "storage", &c.Storage, &ret.Storage)
	translate.MergeP(tr, tm, &r, "systemd", &c.Systemd, &ret.Systemd)

	c.addMountUnits(&ret, &tm)

	tmTrees, rTrees := c.processTrees(&ret, options)
	tmQuadlets, rQuadlets := c.processQuadlets(&ret, options)

	tm.Merge(tmTrees)
	tm.Merge(tmQuadlets)
	r.Merge(rTrees)
	r.Merge(rQuadlets)

	if r.IsFatal() {
		return types.Config{}, translate.TranslationSet{}, r
	}
	return ret, tm, r
}

func translateIgnition(from Ignition, options common.TranslateOptions) (to types.Ignition, tm translate.TranslationSet, r report.Report) {
	tr := translate.NewTranslator("yaml", "json", options)
	tr.AddCustomTranslator(translateResource)
	to.Version = types.MaxVersion.String()
	tm, r = translate.Prefixed(tr, "config", &from.Config, &to.Config)
	translate.MergeP(tr, tm, &r, "proxy", &from.Proxy, &to.Proxy)
	translate.MergeP(tr, tm, &r, "security", &from.Security, &to.Security)
	translate.MergeP(tr, tm, &r, "timeouts", &from.Timeouts, &to.Timeouts)
	return
}

func translateFile(from File, options common.TranslateOptions) (to types.File, tm translate.TranslationSet, r report.Report) {
	tr := translate.NewTranslator("yaml", "json", options)
	tr.AddCustomTranslator(translateResource)
	tm, r = translate.Prefixed(tr, "group", &from.Group, &to.Group)
	translate.MergeP(tr, tm, &r, "user", &from.User, &to.User)
	translate.MergeP(tr, tm, &r, "append", &from.Append, &to.Append)
	translate.MergeP(tr, tm, &r, "contents", &from.Contents, &to.Contents)
	translate.MergeP(tr, tm, &r, "overwrite", &from.Overwrite, &to.Overwrite)
	translate.MergeP(tr, tm, &r, "path", &from.Path, &to.Path)
	translate.MergeP(tr, tm, &r, "mode", &from.Mode, &to.Mode)
	return
}

func translateResource(from Resource, options common.TranslateOptions) (to types.Resource, tm translate.TranslationSet, r report.Report) {
	tr := translate.NewTranslator("yaml", "json", options)
	tm, r = translate.Prefixed(tr, "verification", &from.Verification, &to.Verification)
	translate.MergeP2(tr, tm, &r, "http_headers", &from.HTTPHeaders, "httpHeaders", &to.HTTPHeaders)
	translate.MergeP(tr, tm, &r, "source", &from.Source, &to.Source)
	translate.MergeP(tr, tm, &r, "compression", &from.Compression, &to.Compression)

	if from.Local != nil {
		c := path.New("yaml", "local")
		contents, err := baseutil.ReadLocalFile(*from.Local, options.FilesDir)
		if err != nil {
			r.AddOnError(c, err)
			return
		}
		// Validating the contents of the local file from here since there is no way to
		// get both the filename and filedirectory in the Validate context
		if strings.HasPrefix(c.String(), "$.ignition.config") {
			rp, err := ValidateIgnitionConfig(c, contents)
			r.Merge(rp)
			if err != nil {
				return
			}
		}

		src, compression, err := baseutil.MakeDataURL(contents, to.Compression, !options.NoResourceAutoCompression)
		if err != nil {
			r.AddOnError(c, err)
			return
		}
		to.Source = &src
		tm.AddTranslation(c, path.New("json", "source"))
		if compression != nil {
			to.Compression = compression
			tm.AddTranslation(c, path.New("json", "compression"))
		}
	}

	if from.Inline != nil {
		c := path.New("yaml", "inline")

		src, compression, err := baseutil.MakeDataURL([]byte(*from.Inline), to.Compression, !options.NoResourceAutoCompression)
		if err != nil {
			r.AddOnError(c, err)
			return
		}
		to.Source = &src
		tm.AddTranslation(c, path.New("json", "source"))
		if compression != nil {
			to.Compression = compression
			tm.AddTranslation(c, path.New("json", "compression"))
		}
	}
	return
}

func translateDirectory(from Directory, options common.TranslateOptions) (to types.Directory, tm translate.TranslationSet, r report.Report) {
	tr := translate.NewTranslator("yaml", "json", options)
	tm, r = translate.Prefixed(tr, "group", &from.Group, &to.Group)
	translate.MergeP(tr, tm, &r, "user", &from.User, &to.User)
	translate.MergeP(tr, tm, &r, "overwrite", &from.Overwrite, &to.Overwrite)
	translate.MergeP(tr, tm, &r, "path", &from.Path, &to.Path)
	translate.MergeP(tr, tm, &r, "mode", &from.Mode, &to.Mode)
	return
}

func translateLink(from Link, options common.TranslateOptions) (to types.Link, tm translate.TranslationSet, r report.Report) {
	tr := translate.NewTranslator("yaml", "json", options)
	tm, r = translate.Prefixed(tr, "group", &from.Group, &to.Group)
	translate.MergeP(tr, tm, &r, "user", &from.User, &to.User)
	translate.MergeP(tr, tm, &r, "target", &from.Target, &to.Target)
	translate.MergeP(tr, tm, &r, "hard", &from.Hard, &to.Hard)
	translate.MergeP(tr, tm, &r, "overwrite", &from.Overwrite, &to.Overwrite)
	translate.MergeP(tr, tm, &r, "path", &from.Path, &to.Path)
	return
}

func translatePasswdUser(from PasswdUser, options common.TranslateOptions) (to types.PasswdUser, tm translate.TranslationSet, r report.Report) {
	tr := translate.NewTranslator("yaml", "json", options)
	tm, r = translate.Prefixed(tr, "gecos", &from.Gecos, &to.Gecos)
	translate.MergeP(tr, tm, &r, "groups", &from.Groups, &to.Groups)
	translate.MergeP2(tr, tm, &r, "home_dir", &from.HomeDir, "homeDir", &to.HomeDir)
	translate.MergeP(tr, tm, &r, "name", &from.Name, &to.Name)
	translate.MergeP2(tr, tm, &r, "no_create_home", &from.NoCreateHome, "noCreateHome", &to.NoCreateHome)
	translate.MergeP2(tr, tm, &r, "no_log_init", &from.NoLogInit, "noLogInit", &to.NoLogInit)
	translate.MergeP2(tr, tm, &r, "no_user_group", &from.NoUserGroup, "noUserGroup", &to.NoUserGroup)
	translate.MergeP2(tr, tm, &r, "password_hash", &from.PasswordHash, "passwordHash", &to.PasswordHash)
	translate.MergeP2(tr, tm, &r, "primary_group", &from.PrimaryGroup, "primaryGroup", &to.PrimaryGroup)
	translate.MergeP(tr, tm, &r, "shell", &from.Shell, &to.Shell)
	translate.MergeP2(tr, tm, &r, "should_exist", &from.ShouldExist, "shouldExist", &to.ShouldExist)
	translate.MergeP2(tr, tm, &r, "ssh_authorized_keys", &from.SSHAuthorizedKeys, "sshAuthorizedKeys", &to.SSHAuthorizedKeys)
	translate.MergeP(tr, tm, &r, "system", &from.System, &to.System)
	translate.MergeP(tr, tm, &r, "uid", &from.UID, &to.UID)

	if len(from.SSHAuthorizedKeysLocal) > 0 {
		c := path.New("yaml", "ssh_authorized_keys_local")
		tm.AddTranslation(c, path.New("json", "sshAuthorizedKeys"))

		if options.FilesDir == "" {
			r.AddOnError(c, common.ErrNoFilesDir)
			return
		}

		for keyFileIndex, sshKeyFile := range from.SSHAuthorizedKeysLocal {
			sshKeys, err := baseutil.ReadLocalFile(sshKeyFile, options.FilesDir)
			if err != nil {
				r.AddOnError(c.Append(keyFileIndex), err)
				continue
			}
			for _, line := range regexp.MustCompile("\r?\n").Split(string(sshKeys), -1) {
				if line == "" {
					continue
				}
				tm.AddTranslation(c.Append(keyFileIndex), path.New("json", "sshAuthorizedKeys", len(to.SSHAuthorizedKeys)))
				to.SSHAuthorizedKeys = append(to.SSHAuthorizedKeys, types.SSHAuthorizedKey(line))
			}
		}
	}

	return
}

func translateUnit(from Unit, options common.TranslateOptions) (to types.Unit, tm translate.TranslationSet, r report.Report) {
	tr := translate.NewTranslator("yaml", "json", options)
	tr.AddCustomTranslator(translateDropin)
	tm, r = translate.Prefixed(tr, "contents", &from.Contents, &to.Contents)
	translate.MergeP(tr, tm, &r, "dropins", &from.Dropins, &to.Dropins)
	translate.MergeP(tr, tm, &r, "enabled", &from.Enabled, &to.Enabled)
	translate.MergeP(tr, tm, &r, "mask", &from.Mask, &to.Mask)
	translate.MergeP(tr, tm, &r, "name", &from.Name, &to.Name)

	if util.NotEmpty(from.ContentsLocal) {
		c := path.New("yaml", "contents_local")
		contents, err := baseutil.ReadLocalFile(*from.ContentsLocal, options.FilesDir)
		if err != nil {
			r.AddOnError(c, err)
			return
		}
		tm.AddTranslation(c, path.New("json", "contents"))
		to.Contents = util.StrToPtr(string(contents))
	}

	return
}

func translateDropin(from Dropin, options common.TranslateOptions) (to types.Dropin, tm translate.TranslationSet, r report.Report) {
	tr := translate.NewTranslator("yaml", "json", options)
	tm, r = translate.Prefixed(tr, "contents", &from.Contents, &to.Contents)
	translate.MergeP(tr, tm, &r, "name", &from.Name, &to.Name)

	if util.NotEmpty(from.ContentsLocal) {
		c := path.New("yaml", "contents_local")
		contents, err := baseutil.ReadLocalFile(*from.ContentsLocal, options.FilesDir)
		if err != nil {
			r.AddOnError(c, err)
			return
		}
		tm.AddTranslation(c, path.New("json", "contents"))
		to.Contents = util.StrToPtr(string(contents))
	}

	return
}

// buildQuadletPath returns the filesystem path for a quadlet.
// See https://docs.podman.io/en/latest/markdown/podman-systemd.unit.5.html
func buildQuadletPath(isRoot bool, quadletName string) string {
	const (
		adminContainersPath = "/etc/containers/systemd"
		userContainersPath  = "/etc/containers/systemd/users"
	)
	var base string
	if isRoot {
		base = adminContainersPath
	} else {
		base = userContainersPath
	}
	return slashpath.Join(base, quadletName)
}

// isTemplateInstance checks if a quadlet name is a template instance (e.g. foo@100.container).
// Returns true and the base template name (e.g. foo@.container) if it is an instance.
func isTemplateInstance(name string) (bool, string) {
	splitIndex := strings.Index(name, "@")
	if splitIndex == -1 {
		return false, ""
	}
	extensionIndex := strings.LastIndex(name, ".")
	if extensionIndex == -1 || splitIndex+1 == extensionIndex {
		return false, ""
	}
	baseName := name[:splitIndex]
	extension := name[extensionIndex+1:]
	templateName := fmt.Sprintf("%s@.%s", baseName, extension)
	return true, templateName
}

// readLocalOrInlineContents reads content from either a local file or inline string (see Quadlet and Dropin).
// Returns the content as bytes, the source path for error reporting, and any errors.
func readLocalOrInlineContents(contentsLocal, contentsInline *string, ctxPath path.ContextPath, options common.TranslateOptions) (content []byte, contentPath path.ContextPath, err error) {
	if util.NotEmpty(contentsLocal) {
		contentPath = ctxPath.Append("contents_local")
		localContents, err := baseutil.ReadLocalFile(*contentsLocal, options.FilesDir)
		if err != nil {
			return content, contentPath, err
		}
		content = localContents
	}

	if util.NotEmpty(contentsInline) {
		contentPath = ctxPath.Append("contents")
		content = []byte(*contentsInline)
	}
	return
}

// addFileWithContents reads content (local or inline) and creates a file node in the tracker.
// Used for both quadlet files and their drop-ins, both of which will have either contentsLocal, or contents, but not both.
func addFileWithContents(
	contentsLocal, inlineContents *string,
	destPath string,
	ctxPath path.ContextPath,
	t *nodeTracker,
	options common.TranslateOptions,
) (translate.TranslationSet, report.Report) {
	var r report.Report
	ts := translate.NewTranslationSet("yaml", "json")

	_, file := t.GetFile(destPath)
	// If the node already exists, we dont want to over-write, we will just error
	if (file != nil && util.NotEmpty(file.Contents.Source)) || t.Exists(destPath) {
		r.AddOnError(ctxPath, common.ErrNodeExists)
		return ts, r
	}

	i, file := t.AddFile(types.File{Node: createNode(destPath, NodeUser{}, NodeGroup{})})
	if i == 0 {
		ts.AddTranslation(ctxPath, path.New("json", "storage", "files"))
	}
	ts.AddFromCommonSource(ctxPath, path.New("json", "storage", "files", i), file)
	ts.AddTranslation(ctxPath.Append("name"), path.New("json", "storage", "files", i, "path"))
	contentBytes, contentPath, err := readLocalOrInlineContents(contentsLocal, inlineContents, ctxPath, options)
	if err != nil {
		r.AddOnError(contentPath, err)
		return ts, r
	}
	url, compression, err := baseutil.MakeDataURL(contentBytes, file.Contents.Compression, !options.NoResourceAutoCompression)
	if err != nil {
		r.AddOnError(ctxPath, err)
		return ts, r
	}
	file.Contents.Source = &url
	ts.AddTranslation(contentPath, path.New("json", "storage", "files", i, "contents", "source"))
	if compression != nil {
		file.Contents.Compression = compression
		ts.AddTranslation(ctxPath, path.New("json", "storage", "files", i, "contents", "compression"))
	}
	ts.AddTranslation(contentPath, path.New("json", "storage", "files", i, "contents"))
	if file.Mode == nil {
		mode := 0644
		file.Mode = &mode
		ts.AddTranslation(ctxPath, path.New("json", "storage", "files", i, "mode"))
	}

	return ts, r
}

// quadletToSymlink creates a symlink node for a template instance pointing to its base template.
func quadletToSymlink(quadlet Quadlet, quadletPath path.ContextPath, t *nodeTracker, templateName string) (translate.TranslationSet, report.Report) {
	var r report.Report
	ts := translate.NewTranslationSet("yaml", "json")

	destPath := buildQuadletPath(quadlet.Rootful, quadlet.Name)
	_, link := t.GetLink(destPath)
	// If the node already exists, we don't want to over-write, we will just error
	if link != nil || t.Exists(destPath) {
		r.AddOnError(quadletPath, common.ErrNodeExists)
		return ts, r
	}

	i, link := t.AddLink(types.Link{Node: types.Node{Path: destPath}, LinkEmbedded1: types.LinkEmbedded1{
		Target: &templateName,
	}})
	if i == 0 {
		ts.AddTranslation(quadletPath, path.New("json", "storage", "links"))
	}
	ts.AddFromCommonSource(quadletPath, path.New("json", "storage", "links", i), link)
	ts.AddTranslation(quadletPath.Append("name"), path.New("json", "storage", "links", i, "path"))
	ts.AddTranslation(quadletPath, path.New("json", "storage", "links", i, "target"))
	return ts, r
}

func (c Config) processQuadlets(ret *types.Config, options common.TranslateOptions) (translate.TranslationSet, report.Report) {
	ts := translate.NewTranslationSet("yaml", "json")
	var r report.Report
	if len(c.Systemd.Quadlets) == 0 {
		return ts, r
	}

	t := newNodeTracker(ret)
	quadletsPath := path.New("yaml", "systemd", "quadlets")
	ts.AddTranslation(quadletsPath, path.New("json", "storage")) // quadlets will be translated to storage (files and links)
	for quadletNum, quadlet := range c.Systemd.Quadlets {
		quadletPath := quadletsPath.Append(quadletNum)

		// We need to handle `foo@bar.container` differently than `foo@.container`, as the former needs to be a symlink to the latter
		var tsFile translate.TranslationSet
		var rFile report.Report
		if isTemplate, templateName := isTemplateInstance(quadlet.Name); isTemplate {
			tsFile, rFile = quadletToSymlink(quadlet, quadletPath, t, templateName)
		} else {
			destPath := buildQuadletPath(quadlet.Rootful, quadlet.Name)
			tsFile, rFile = addFileWithContents(quadlet.ContentsLocal, quadlet.Contents, destPath, quadletPath, t, options)
		}

		ts.Merge(tsFile)
		r.Merge(rFile)

		for i, dropin := range quadlet.Dropins {
			dropinPath := quadletPath.Append("dropins").Append(i)
			destPath := buildQuadletPath(quadlet.Rootful, quadlet.Name) + ".d/" + dropin.Name
			tsFile, rFile := addFileWithContents(dropin.ContentsLocal, dropin.Contents, destPath, dropinPath, t, options)
			ts.Merge(tsFile)
			r.Merge(rFile)
		}
	}

	return ts, r
}

func (c Config) processTrees(ret *types.Config, options common.TranslateOptions) (translate.TranslationSet, report.Report) {
	ts := translate.NewTranslationSet("yaml", "json")
	var r report.Report
	if len(c.Storage.Trees) == 0 {
		return ts, r
	}
	t := newNodeTracker(ret)

	for i, tree := range c.Storage.Trees {
		yamlPath := path.New("yaml", "storage", "trees", i)
		if options.FilesDir == "" {
			r.AddOnError(yamlPath, common.ErrNoFilesDir)
			return ts, r
		}

		// calculate base path within FilesDir and check for
		// path traversal
		srcBaseDir := filepath.Join(options.FilesDir, filepath.FromSlash(tree.Local))
		if err := baseutil.EnsurePathWithinFilesDir(srcBaseDir, options.FilesDir); err != nil {
			r.AddOnError(yamlPath, err)
			continue
		}
		info, err := os.Stat(srcBaseDir)
		if err != nil {
			r.AddOnError(yamlPath, err)
			continue
		}
		if !info.IsDir() {
			r.AddOnError(yamlPath, common.ErrTreeNotDirectory)
			continue
		}
		destBaseDir := "/"
		if util.NotEmpty(tree.Path) {
			destBaseDir = *tree.Path
		}

		walkTree(yamlPath, &ts, &r, t, treeWalkOptions{
			srcBaseDir:       srcBaseDir,
			destBaseDir:      destBaseDir,
			TranslateOptions: options,
			user:             tree.User,
			group:            tree.Group,
			fileMode:         tree.FileMode,
			dirMode:          tree.DirMode,
		})
	}
	return ts, r
}

type treeWalkOptions struct {
	srcBaseDir  string
	destBaseDir string
	common.TranslateOptions
	user     NodeUser
	group    NodeGroup
	fileMode *int
	dirMode  *int
}

func walkTree(yamlPath path.ContextPath, ts *translate.TranslationSet, r *report.Report, t *nodeTracker, options treeWalkOptions) {
	// The strategy for errors within WalkFunc is to add an error to
	// the report and return nil, so walking continues but translation
	// will fail afterward.
	err := filepath.Walk(options.srcBaseDir, func(srcPath string, info os.FileInfo, err error) error {
		if err != nil {
			r.AddOnError(yamlPath, err)
			return nil
		}
		relPath, err := filepath.Rel(options.srcBaseDir, srcPath)
		if err != nil {
			r.AddOnError(yamlPath, err)
			return nil
		}
		destPath := slashpath.Join(options.destBaseDir, filepath.ToSlash(relPath))

		if info.Mode().IsDir() {
			// If nothing custom is required we skip directories generation
			if options.dirMode == nil && options.user == (NodeUser{}) && options.group == (NodeGroup{}) {
				return nil
			}

			if t.Exists(destPath) {
				r.AddOnError(yamlPath, common.ErrNodeExists)
				return nil
			}
			mode := util.IntToPtr(0755)
			if options.dirMode != nil {
				mode = options.dirMode
			}
			i, dir := t.AddDir(types.Directory{
				Node: createNode(destPath, options.user, options.group),
				DirectoryEmbedded1: types.DirectoryEmbedded1{
					Mode: mode,
				},
			})
			ts.AddFromCommonSource(yamlPath, path.New("json", "storage", "directories", i), dir)
			if i == 0 {
				ts.AddTranslation(yamlPath, path.New("json", "storage", "directories"))
			}
		} else if info.Mode().IsRegular() {
			i, file := t.GetFile(destPath)
			if file != nil {
				if util.NotEmpty(file.Contents.Source) {
					r.AddOnError(yamlPath, common.ErrNodeExists)
					return nil
				}
			} else {
				if t.Exists(destPath) {
					r.AddOnError(yamlPath, common.ErrNodeExists)
					return nil
				}
				i, file = t.AddFile(types.File{
					Node: createNode(destPath, options.user, options.group),
				})
				ts.AddFromCommonSource(yamlPath, path.New("json", "storage", "files", i), file)
				if i == 0 {
					ts.AddTranslation(yamlPath, path.New("json", "storage", "files"))
				}
			}
			contents, err := os.ReadFile(srcPath)
			if err != nil {
				r.AddOnError(yamlPath, err)
				return nil
			}
			url, compression, err := baseutil.MakeDataURL(contents, file.Contents.Compression, !options.NoResourceAutoCompression)
			if err != nil {
				r.AddOnError(yamlPath, err)
				return nil
			}
			file.Contents.Source = &url
			ts.AddTranslation(yamlPath, path.New("json", "storage", "files", i, "contents", "source"))
			if compression != nil {
				file.Contents.Compression = compression
				ts.AddTranslation(yamlPath, path.New("json", "storage", "files", i, "contents", "compression"))
			}
			ts.AddTranslation(yamlPath, path.New("json", "storage", "files", i, "contents"))
			if file.Mode == nil {
				mode := 0644
				if info.Mode()&0111 != 0 {
					mode = 0755
				}
				if options.fileMode != nil {
					mode = *options.fileMode
				}
				file.Mode = &mode
				ts.AddTranslation(yamlPath, path.New("json", "storage", "files", i, "mode"))
			}
		} else if info.Mode()&os.ModeType == os.ModeSymlink {
			i, link := t.GetLink(destPath)
			if link != nil {
				if util.NotEmpty(link.Target) {
					r.AddOnError(yamlPath, common.ErrNodeExists)
					return nil
				}
			} else {
				if t.Exists(destPath) {
					r.AddOnError(yamlPath, common.ErrNodeExists)
					return nil
				}
				i, link = t.AddLink(types.Link{
					Node: createNode(destPath, options.user, options.group),
				})
				ts.AddFromCommonSource(yamlPath, path.New("json", "storage", "links", i), link)
				if i == 0 {
					ts.AddTranslation(yamlPath, path.New("json", "storage", "links"))
				}
			}
			target, err := os.Readlink(srcPath)
			if err != nil {
				r.AddOnError(yamlPath, err)
				return nil
			}
			link.Target = util.StrToPtr(filepath.ToSlash(target))
			ts.AddTranslation(yamlPath, path.New("json", "storage", "links", i, "target"))
		} else {
			r.AddOnError(yamlPath, common.ErrFileType)
			return nil
		}
		return nil
	})
	r.AddOnError(yamlPath, err)
}

func createNode(destPath string, user NodeUser, group NodeGroup) types.Node {
	return types.Node{
		Path: destPath,
		User: types.NodeUser{
			ID:   user.ID,
			Name: user.Name,
		},
		Group: types.NodeGroup{
			ID:   group.ID,
			Name: group.Name,
		},
	}
}

func (c Config) addMountUnits(config *types.Config, ts *translate.TranslationSet) {
	if len(c.Storage.Filesystems) == 0 {
		return
	}
	var rendered types.Config
	renderedTranslations := translate.NewTranslationSet("yaml", "json")
	renderedTranslations.AddTranslation(path.New("yaml", "storage", "filesystems"), path.New("json", "systemd"))
	renderedTranslations.AddTranslation(path.New("yaml", "storage", "filesystems"), path.New("json", "systemd", "units"))
	for i, fs := range c.Storage.Filesystems {
		if !util.IsTrue(fs.WithMountUnit) {
			continue
		}
		fromPath := path.New("yaml", "storage", "filesystems", i, "with_mount_unit")
		remote := false
		// check filesystems targeting /dev/mapper devices against LUKS to determine if a
		// remote mount is needed
		if strings.HasPrefix(fs.Device, "/dev/mapper/") || strings.HasPrefix(fs.Device, "/dev/disk/by-id/dm-name-") {
			for _, luks := range c.Storage.Luks {
				// LUKS devices are opened with their name specified
				if fs.Device == fmt.Sprintf("/dev/mapper/%s", luks.Name) || fs.Device == fmt.Sprintf("/dev/disk/by-id/dm-name-%s", luks.Name) {
					if len(luks.Clevis.Tang) > 0 {
						remote = true
						break
					}
				}
			}
		}
		newUnit := mountUnitFromFS(fs, remote)
		unitPath := path.New("json", "systemd", "units", len(rendered.Systemd.Units))
		rendered.Systemd.Units = append(rendered.Systemd.Units, newUnit)
		renderedTranslations.AddFromCommonSource(fromPath, unitPath, newUnit)
	}
	retConfig, retTranslations := baseutil.MergeTranslatedConfigs(rendered, renderedTranslations, *config, *ts)
	*config = retConfig.(types.Config)
	*ts = retTranslations
}

func mountUnitFromFS(fs Filesystem, remote bool) types.Unit {
	context := struct {
		*Filesystem
		EscapedDevice string
		Remote        bool
		Swap          bool
	}{
		Filesystem:    &fs,
		EscapedDevice: unit.UnitNamePathEscape(fs.Device),
		Remote:        remote,
		// unchecked deref of format ok, fs would fail validation otherwise
		Swap: *fs.Format == "swap",
	}
	contents := strings.Builder{}
	err := mountUnitTemplate.Execute(&contents, context)
	if err != nil {
		panic(err)
	}
	var unitName string
	if context.Swap {
		unitName = unit.UnitNamePathEscape(fs.Device) + ".swap"
	} else {
		// unchecked deref of path ok, fs would fail validation otherwise
		unitName = unit.UnitNamePathEscape(*fs.Path) + ".mount"
	}
	return types.Unit{
		Name:     unitName,
		Enabled:  util.BoolToPtr(true),
		Contents: util.StrToPtr(contents.String()),
	}
}
