FROM golang:latest AS builder
RUN mkdir /ignition-validate
COPY . /ignition-validate
WORKDIR /ignition-validate
RUN ./build_releases

FROM scratch
COPY --from=builder /ignition-validate/bin/releases/ignition-validate-x86_64-unknown-linux-gnu /usr/local/bin/ignition-validate
ENTRYPOINT ["/usr/local/bin/ignition-validate"]
