#!/bin/bash -eu

source ./build

SRC="
	config
	config/types
	config/v1
	config/v1/types
	internal
	internal/exec
	internal/exec/stages
	internal/exec/stages/disks
	internal/exec/stages/files
	internal/exec/util
	internal/providers
	internal/providers/cmdline
	internal/providers/ec2
	internal/providers/util
	internal/registry
	internal/util
	internal/util/tools
"

echo "Checking gofix..."
go tool fix -diff $SRC

echo "Checking gofmt..."
res=$(gofmt -d -e -s $SRC)
echo "${res}"
if [ -n "${res}" ]; then
	exit 1
fi

# split SRC into an array and prepend REPO_PATH to each local package for go vet
split_vet=(${SRC// / })
VET_TEST=${split_vet[@]/#/${REPO_PATH}/}

echo "Checking govet..."
go vet $VET_TEST

echo "Running tests..."
go test -timeout 60s -cover $@ ${VET_TEST} --race

echo "Success"
