#!/usr/bin/env bash

set -eu

export GO111MODULE=on
export GOFLAGS=-mod=vendor
export CGO_ENABLED=0

if [ -z ${VERSION+a} ]; then
	VERSION=$(git describe --dirty --always)
fi

LDFLAGS="-w -X github.com/coreos/ignition/v2/butane/internal/version.Raw=$VERSION"

NAME=butane

if [ -z ${BIN_PATH+a} ]; then
	BIN_PATH=${PWD}/bin/$(go env GOARCH)
fi

echo "Building $NAME..."
go build -o ${BIN_PATH}/${NAME} -ldflags "$LDFLAGS" github.com/coreos/ignition/v2/butane/internal
