#!/bin/sh -e
# -*- mode: shell-script; indent-tabs-mode: nil; sh-basic-offset: 4; -*-
# ex: ts=8 sw=4 sts=4 et filetype=sh

# /etc/machine-id after a new image is created:
COREOS_BLANK_MACHINE_ID="42000000000000000000000000000042"
MACHINE_ID_FILE="/sysroot/etc/machine-id"

do_setup_root() {
    # Initialize base filesystem
    systemd-tmpfiles --root=/sysroot --create \
        baselayout.conf baselayout-etc.conf baselayout-usr.conf \
        baselayout-home.conf etc.conf libsemanage.conf selinux-base.conf

    # Not all images provide this file so check before using it.
    if [ -e "/sysroot/usr/lib/tmpfiles.d/baselayout-ldso.conf" ]; then
        systemd-tmpfiles --root=/sysroot --create \
            baselayout-ldso.conf
    fi

    # This creates the modifiable users/groups in /sysroot/etc,
    # initializing the shadow database in the process.
    /usr/sbin/coreos-tmpfiles /sysroot

    # Remove our phony id. systemd will initialize this during boot.
    if grep -qs "${COREOS_BLANK_MACHINE_ID}" "${MACHINE_ID_FILE}"; then
        rm "${MACHINE_ID_FILE}"
    fi
}

# Skip if root and root/usr are not mount points
if mountpoint --quiet /sysroot && mountpoint --quiet /sysroot/usr; then
    do_setup_root
fi

# PXE initrds may provide OEM
if [ -d /usr/share/oem ] && mountpoint --quiet /sysroot/usr/share/oem; then
    cp -Ra /usr/share/oem/. /sysroot/usr/share/oem
fi
